version: '3'

services:
  rabbit-mq:
    image: rabbitmq:3-management
    container_name: swa_rabbit_mq
    networks:
      - network
    expose:
      - 5672
    ports:
    - 15672:15672
    restart: on-failure

  app:
    container_name: swa_rabbitmq_testapp
    build:
      context: .
      dockerfile: "Dockerfile"
    image: rabbitmq-test
    networks:
      - network
    environment:
      RABBIT_MQ_HOST: "rabbit-mq"
    depends_on:
      - rabbit-mq
    restart: on-failure

networks:
  network:
    driver: bridge

